name: testing_flutter_for_real_now
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Service locator
  get_it: ^2.0.1
  #Bloc for state management
  flutter_bloc: ^0.21.0
  #Value equality
  equatable: ^0.4.0
  #Functional programming thingies
  dartz: ^0.8.6
  #Remote API
  data_connection_checker:
  http: ^0.12.0+2
  #Local cache
  shared_preferences: ^0.5.3+4

  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  #TODO FIX MOCKITO
  mockito: 5.3.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true